name: validation

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: install latest TASCAR from github
      run: wget https://www.tascar.org/tascar_installer.sh && chmod +x tascar_installer.sh && 
           sudo sudo ./tascar_installer.sh
    - name: validate
      run: make -C test
